-- -----------------------------------------------------
-- Data for table `cmmi`.`cmmi_pacamls`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
USE `cmmi`;

INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (1,1,1,1,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (2,1,2,1,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (3,1,3,1,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (4,1,4,1,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (5,1,5,5,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (6,3,6,4,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (7,3,7,7,5) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (8,1,7,7,5) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (9,2,7,7,5) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (10,3,8,7,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (11,1,8,7,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (12,2,8,7,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (13,3,9,7,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (14,1,9,7,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (15,2,9,7,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (16,3,10,6,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (17,1,11,5,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (18,2,11,5,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (19,3,12,4,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (20,3,13,7,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (21,1,13,7,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (22,2,13,7,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (23,3,14,3,5) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (24,1,14,3,5) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (25,2,14,3,5) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (26,3,15,3,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (27,1,15,3,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (28,2,15,3,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (29,3,16,3,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (30,1,16,3,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (31,2,16,3,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (32,3,17,3,4) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (33,1,17,3,4) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (34,2,17,3,4) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (35,3,18,3,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (36,1,18,3,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (37,2,18,3,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (38,2,19,7,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (39,3,19,7,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (40,1,19,7,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (41,2,20,2,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (42,1,21,5,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (43,2,21,5,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (44,1,22,5,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (45,2,22,5,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (46,2,23,5,4) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (47,1,23,5,4) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (48,3,24,4,4) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (49,2,25,2,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (50,2,26,5,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (51,3,26,4,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (52,1,26,5,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (53,3,27,4,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (54,2,27,5,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (55,1,27,5,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (56,3,28,4,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (57,3,29,6,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (58,3,30,6,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (59,3,31,6,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (60,1,32,5,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (61,3,33,6,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (62,2,34,5,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (63,3,34,4,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (64,2,35,2,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (65,2,36,2,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (66,2,37,2,3) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (67,3,38,4,2) ;
INSERT INTO  `cmmi`.`cmmi_pacamls` ( `id`, `type_id`, `process_area_id`, `category_id`, `maturity_level_id`) VALUES (68,3,39,4,2) ;

commit;
